# Generated by Django 2.2.5 on 2019-10-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transform',
            name='is_used_as_view',
        ),
        migrations.RemoveField(
            model_name='transform',
            name='sink',
        ),
        migrations.RemoveField(
            model_name='transform',
            name='use_self',
        ),
        migrations.AddField(
            model_name='transform',
            name='yaml',
            field=models.TextField(default='', verbose_name='其他信息(yaml格式)'),
        ),
    ]
