# Generated by Django 2.1 on 2019-10-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0002_auto_20191010_2133'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='resource',
            index_together=set(),
        ),
    ]
