# Generated by Django 2.2.6 on 2019-12-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0003_auto_20191012_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_publish', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('create_by', models.IntegerField(default=0, verbose_name='创建用户ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='名字')),
                ('info', models.CharField(blank=True, max_length=2048, null=True, verbose_name='介绍')),
                ('cache', models.TextField(verbose_name='缓存')),
                ('typ', models.CharField(choices=[('json', 'json'), ('yml', 'yml')], default='yml', max_length=256, verbose_name='类型')),
                ('config', models.TextField(verbose_name='配置')),
            ],
            options={
                'db_table': 'relationship',
                'unique_together': {('create_by', 'name')},
                'index_together': {('create_by', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_publish', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('create_by', models.IntegerField(default=0, verbose_name='创建用户ID')),
                ('name', models.CharField(max_length=256, verbose_name='名字')),
                ('typ', models.CharField(max_length=256, verbose_name='类型')),
                ('suffix', models.CharField(blank=True, max_length=32, null=True, verbose_name='自主后缀')),
                ('username', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=256, null=True, verbose_name='密码')),
                ('info', models.CharField(blank=True, max_length=2048, null=True, verbose_name='介绍')),
                ('url', models.CharField(blank=True, max_length=2048, null=True, verbose_name='链接信息')),
                ('cache', models.TextField(verbose_name='缓存')),
                ('update_interval', models.IntegerField(default=3600, verbose_name='更新间隔（秒）')),
            ],
            options={
                'db_table': 'connection',
                'unique_together': {('create_by', 'name')},
                'index_together': {('create_by', 'name')},
            },
        ),
    ]
