# Generated by Django 2.2.6 on 2019-12-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0004_connection_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='cache',
            field=models.TextField(blank=True, null=True, verbose_name='缓存'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='url',
            field=models.CharField(max_length=2048, verbose_name='链接信息'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='cache',
            field=models.TextField(blank=True, null=True, verbose_name='缓存'),
        ),
    ]
