# Generated by Django 2.2.6 on 2019-12-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0006_relationship_update_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='table_exclude_regex',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='真实数据库与表名排除正则(逗号分隔)'),
        ),
        migrations.AddField(
            model_name='connection',
            name='table_regex',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='真实数据库与表名过滤正则(逗号分隔)'),
        ),
    ]
