# Generated by Django 3.0 on 2019-12-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0007_auto_20191230_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='cache',
            field=models.BinaryField(blank=True, null=True, verbose_name='缓存'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='cache',
            field=models.BinaryField(blank=True, null=True, verbose_name='缓存'),
        ),
    ]
